"""tamabah relasi antara ata dan job request

Revision ID: 21479f0cc8ff
Revises: 724e34cb516b
Create Date: 2026-01-15 14:35:06.527487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21479f0cc8ff'
down_revision = '724e34cb516b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ata_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'job_positions', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ata_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
