"""menambahkan fitur dasar tracing dan ata

Revision ID: 724e34cb516b
Revises: 
Create Date: 2026-01-15 09:20:48.073815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '724e34cb516b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ata_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('salary_min', sa.BigInteger(), nullable=True),
    sa.Column('salary_max', sa.BigInteger(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('hr_status', sa.String(length=20), nullable=True),
    sa.Column('hr_notes', sa.String(), nullable=True),
    sa.Column('hr_date', sa.DateTime(), nullable=True),
    sa.Column('ktt_status', sa.String(length=20), nullable=True),
    sa.Column('ktt_notes', sa.String(), nullable=True),
    sa.Column('ktt_date', sa.DateTime(), nullable=True),
    sa.Column('ho_status', sa.String(length=20), nullable=True),
    sa.Column('ho_notes', sa.String(), nullable=True),
    sa.Column('ho_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cfit_norma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_score', sa.Integer(), nullable=True),
    sa.Column('iq_score', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_score')
    )
    op.create_table('cfit_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtest', sa.Integer(), nullable=True),
    sa.Column('subtest_name', sa.String(length=100), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('options', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='job_priority_types'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'closed', name='job_status_types'), nullable=False),
    sa.Column('salary_min', sa.BigInteger(), nullable=True),
    sa.Column('salary_max', sa.BigInteger(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kraepelin_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('duration_per_column', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papi_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_a', sa.Text(), nullable=True),
    sa.Column('statement_b', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papi_scoring_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('choice', sa.String(length=1), nullable=True),
    sa.Column('aspect', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('index_path', sa.Text(), nullable=True),
    sa.Column('chunks_path', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_USER', 'HR', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)

    op.create_table('job_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('ai_verdict', sa.Text(), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('Applied', 'Screening', 'Psychotest', 'Interview', 'Offer', 'Hired', 'Rejected', name='app_status'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='_candidate_job_uc')
    )
    op.create_table('test_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('recruitment_journeys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('current_stage', sa.Enum('CV_SCREENING', 'AI_SCREENING', 'RANKING', 'PSYCHOTEST', 'INTERVIEW_HR', 'INTERVIEW_USER', 'OFFERING', 'NEGOTIATION', 'TICKET', 'HIRED', 'REJECTED', 'MCU_PROCESS', 'MCU_REVIEW', 'MCU_FAILED', 'OFFERING_DECLINED', 'ONBOARDING', 'HR_REVIEW', 'FINAL_SELECTION', 'OFFERING_ACCEPTED', name='recruitment_stage_enum'), nullable=False),
    sa.Column('stage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('test_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('test_type', sa.String(length=20), nullable=True),
    sa.Column('raw_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['test_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journey_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('previous_stage', sa.String(length=50), nullable=True),
    sa.Column('new_stage', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['recruitment_journeys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_logs')
    op.drop_table('test_submissions')
    op.drop_table('recruitment_journeys')
    op.drop_table('test_links')
    op.drop_table('job_applications')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_email'))

    op.drop_table('candidates')
    op.drop_table('users')
    op.drop_table('resumes')
    op.drop_table('papi_scoring_map')
    op.drop_table('papi_questions')
    op.drop_table('kraepelin_configs')
    op.drop_table('job_positions')
    op.drop_table('cfit_questions')
    op.drop_table('cfit_norma')
    op.drop_table('ata_requests')
    # ### end Alembic commands ###
